# Generated by Django 5.2.7 on 2025-12-06 12:50

import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='班级名称，格式：XXXX年[专业名称][学制标签]-X班', max_length=100)),
                ('enrollment_year', models.IntegerField(default=2024, help_text='入学年份', validators=[organization.models.validate_enrollment_year])),
                ('class_number', models.IntegerField(default=1, help_text='班级序号')),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(help_text='学院代码，4位数字，符合GB/T 13745标准', max_length=20, unique=True, validators=[organization.models.validate_college_code])),
                ('name', models.CharField(help_text='学院名称', max_length=100)),
                ('establishment_date', models.DateField(help_text='成立日期')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', help_text='学院状态', max_length=20)),
            ],
            options={
                'db_table': 'colleges',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(help_text='专业代码，6位数字', max_length=20, unique=True, validators=[organization.models.validate_major_code])),
                ('name', models.CharField(help_text='专业名称', max_length=100)),
                ('duration_type', models.CharField(choices=[('3_year', '3年制'), ('5_year', '5年制'), ('6_year', '6年制')], default='3_year', help_text='学制类型', max_length=20)),
            ],
            options={
                'db_table': 'majors',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(help_text='操作人ID')),
                ('operation_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('import', '导入'), ('export', '导出')], help_text='操作类型', max_length=20)),
                ('table_name', models.CharField(help_text='表名', max_length=50)),
                ('record_id', models.CharField(help_text='记录ID', max_length=50)),
                ('old_data', models.JSONField(default=dict, help_text='修改前数据')),
                ('new_data', models.JSONField(default=dict, help_text='修改后数据')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP地址', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='用户代理')),
            ],
            options={
                'db_table': 'operation_logs',
            },
        ),
        migrations.CreateModel(
            name='SystemDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('dict_type', models.CharField(help_text='字典类型', max_length=50)),
                ('dict_key', models.CharField(help_text='字典键', max_length=50)),
                ('dict_value', models.CharField(help_text='字典值', max_length=100)),
                ('sort_order', models.IntegerField(default=0, help_text='排序')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
            ],
            options={
                'db_table': 'system_dictionaries',
            },
        ),
    ]
