# Generated by Django 5.2.7 on 2025-12-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='head_teacher',
            field=models.OneToOneField(blank=True, help_text='班主任', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to='personnel.teacher'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['code', 'name'], name='colleges_code_0c95b9_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['status'], name='colleges_status_e33a19_idx'),
        ),
        migrations.AddField(
            model_name='major',
            name='college',
            field=models.ForeignKey(help_text='所属学院', on_delete=django.db.models.deletion.PROTECT, related_name='majors', to='organization.college'),
        ),
        migrations.AddField(
            model_name='class',
            name='major',
            field=models.ForeignKey(help_text='所属专业', on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='organization.major'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['user_id', 'operation_type'], name='operation_l_user_id_d2f79d_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['table_name', 'record_id'], name='operation_l_table_n_e7a9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['created_at'], name='operation_l_created_3fec78_idx'),
        ),
        migrations.AddIndex(
            model_name='systemdictionary',
            index=models.Index(fields=['dict_type'], name='system_dict_dict_ty_747ced_idx'),
        ),
        migrations.AddIndex(
            model_name='systemdictionary',
            index=models.Index(fields=['dict_type', 'is_active'], name='system_dict_dict_ty_7a55d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='systemdictionary',
            unique_together={('dict_type', 'dict_key')},
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['college', 'duration_type'], name='majors_college_8990d1_idx'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['code'], name='majors_code_e8aa57_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['major', 'enrollment_year'], name='classes_major_i_f9dbed_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['enrollment_year'], name='classes_enrollm_c464ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('major', 'enrollment_year', 'class_number')},
        ),
    ]
