# Generated by Django 5.2.7 on 2025-12-06 16:00

import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='code',
            field=models.CharField(help_text='专业代码，2位数字', max_length=20, validators=[organization.models.validate_major_code]),
        ),
        migrations.AlterUniqueTogether(
            name='major',
            unique_together={('college', 'code')},
        ),
    ]
