# Generated by Django 5.2.7 on 2025-12-06 16:28

import django.utils.timezone
import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_class_created_at_alter_college_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='major',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_number',
            field=models.IntegerField(default=1, help_text='班级ID（1位数字）', validators=[organization.models.validate_class_number]),
        ),
        migrations.AlterField(
            model_name='class',
            name='enrollment_year',
            field=models.IntegerField(default=2024, help_text='年级ID（4位数字）', validators=[organization.models.validate_enrollment_year]),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='班级名称，自动生成公式：年级ID+学院ID+班级ID', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(help_text='学院ID，2位数字，唯一标识', max_length=20, unique=True, validators=[organization.models.validate_college_code]),
        ),
        migrations.AlterField(
            model_name='college',
            name='establishment_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='成立日期'),
        ),
        migrations.AlterField(
            model_name='major',
            name='code',
            field=models.CharField(help_text='专业ID，3位数字，唯一标识', max_length=20, unique=True, validators=[organization.models.validate_major_code]),
        ),
    ]
