# Generated by Django 5.2.7 on 2025-12-07 15:27

import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_major_unique_together_alter_class_class_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='code',
            field=models.CharField(help_text='专业ID，2位数字，唯一标识', max_length=20, unique=True, validators=[organization.models.validate_major_code]),
        ),
    ]
