# Generated by Django 5.2.7 on 2025-12-17 17:15

import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_update_class_ids'),
    ]

    operations = [
        # 注意：class_id 字段已经存在于 models.py 和数据库中，
        # 此迁移不再对唯一约束做额外调整，只更新字段定义，避免重复索引错误。
        migrations.AlterField(
            model_name='class',
            name='class_number',
            field=models.IntegerField(
                default=1,
                help_text='班级序号（1位数字）',
                validators=[organization.models.validate_class_number],
            ),
        ),
    ]
