# Generated by Django 5.2.7 on 2025-12-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_add_courseschedule_indexes'),
    ]

    operations = [
        # class_id 字段已经在当前正式数据库中存在，这里不再执行任何结构变更，
        # 仅保留空迁移用于保证迁移链完整，避免重复添加字段或索引报错。
    ]
