# Generated by Django 5.2.7 on 2025-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', '正常'), ('late', '迟到'), ('absent', '缺勤'), ('leave', '请假')], max_length=16)),
                ('remark', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
