# Generated by Django 5.2.7 on 2025-12-06 12:50

import django.db.models.deletion
import organization.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(help_text='权限代码', max_length=100, unique=True)),
                ('name', models.CharField(help_text='权限名称', max_length=100)),
                ('module', models.CharField(help_text='所属模块', max_length=50)),
                ('description', models.TextField(blank=True, help_text='权限描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
            ],
            options={
                'db_table': 'permissions',
                'indexes': [models.Index(fields=['module'], name='permissions_module_2c0512_idx'), models.Index(fields=['is_active'], name='permissions_is_acti_cb1682_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='角色名称', max_length=50, unique=True)),
                ('code', models.CharField(help_text='角色代码', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='角色描述')),
                ('permissions', models.JSONField(default=list, help_text='权限列表，JSON数组')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
            ],
            options={
                'db_table': 'roles',
                'indexes': [models.Index(fields=['code'], name='roles_code_25c050_idx'), models.Index(fields=['is_active'], name='roles_is_acti_723ee4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created_at', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_id', models.CharField(help_text='工号，主键', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='姓名', max_length=50)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], help_text='性别', max_length=10)),
                ('contact_info', models.JSONField(default=dict, help_text='联系方式，JSON格式，包含phone和email', validators=[organization.models.validate_contact_info])),
                ('hire_date', models.DateField(help_text='入职日期')),
                ('position_type', models.CharField(choices=[('dean', '院长'), ('vice_dean', '副院长'), ('head_teacher', '班主任'), ('teacher', '教师')], help_text='职务类型', max_length=20)),
                ('managed_majors', models.JSONField(default=list, help_text='管辖专业IDs，JSON数组')),
                ('college', models.ForeignKey(blank=True, help_text='所属学院', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='organization.college')),
                ('managed_class', models.OneToOneField(blank=True, help_text='负责班级', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_teacher_profile', to='organization.class')),
                ('user', models.OneToOneField(blank=True, help_text='关联用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='TeacherPositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('old_position', models.CharField(blank=True, choices=[('dean', '院长'), ('vice_dean', '副院长'), ('head_teacher', '班主任'), ('teacher', '教师')], help_text='原职务', max_length=20, null=True)),
                ('new_position', models.CharField(choices=[('dean', '院长'), ('vice_dean', '副院长'), ('head_teacher', '班主任'), ('teacher', '教师')], help_text='新职务', max_length=20)),
                ('change_reason', models.TextField(blank=True, help_text='变更原因')),
                ('effective_date', models.DateField(help_text='生效日期')),
                ('changed_by', models.ForeignKey(help_text='变更人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_position_changes', to=settings.AUTH_USER_MODEL)),
                ('new_college', models.ForeignKey(blank=True, help_text='新学院', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_history_new', to='organization.college')),
                ('old_college', models.ForeignKey(blank=True, help_text='原学院', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_history_old', to='organization.college')),
                ('teacher', models.ForeignKey(help_text='教师', on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='personnel.teacher')),
            ],
            options={
                'db_table': 'teacher_position_history',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='分配时间')),
                ('assigned_by', models.ForeignKey(help_text='分配人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='角色', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='personnel.role')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['college', 'position_type'], name='teachers_college_b13056_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='teachers_name_13cfbe_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['position_type'], name='teachers_positio_1bbd52_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(condition=models.Q(('position_type', 'dean')), fields=('college', 'position_type'), name='unique_college_dean'),
        ),
        migrations.AddIndex(
            model_name='teacherpositionhistory',
            index=models.Index(fields=['teacher', 'effective_date'], name='teacher_pos_teacher_a130d9_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpositionhistory',
            index=models.Index(fields=['changed_by'], name='teacher_pos_changed_fccba1_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user'], name='user_roles_user_id_05df60_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='user_roles_role_id_0b583b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
