# Generated by Django 5.2.7 on 2025-12-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='期末分'),
        ),
        migrations.AddField(
            model_name='grade',
            name='final_weight',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='期末分占比(%)'),
        ),
        migrations.AddField(
            model_name='grade',
            name='regular_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='平时分'),
        ),
        migrations.AddField(
            model_name='grade',
            name='regular_weight',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='平时分占比(%)'),
        ),
        migrations.AddField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
