# Generated by Django 5.2.7 on 2025-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('capacity', models.IntegerField(default=50)),
                ('status', models.CharField(default='可用', max_length=20)),
            ],
        ),
    ]
