# Generated by Django 5.2.7 on 2025-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
