# Generated by Django 5.2.7 on 2025-12-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_teacherprofile_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='dorm_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='宿舍号'),
        ),
    ]
