# Generated by Django 5.2.7 on 2025-12-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='职务'),
        ),
    ]
