# Generated by Django 5.2.7 on 2025-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('campus', '全校活动'), ('teaching', '教学安排'), ('meeting', '会议'), ('custom', '自定义')], max_length=16)),
                ('visibility', models.CharField(choices=[('all', '全校'), ('college', '指定学院'), ('role', '指定职务'), ('personal', '个人')], default='all', max_length=16)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('remind_minutes_before', models.IntegerField(default=0)),
            ],
        ),
    ]
