# Generated by Django 5.2.7 on 2025-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(default='SUB001', max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('course_type', models.CharField(choices=[('required', '必修'), ('elective', '选修'), ('practical', '实践')], max_length=16)),
                ('edu_level', models.CharField(choices=[('high_school', '高中'), ('junior_college', '大专'), ('undergraduate', '本科'), ('postgraduate', '研究生')], max_length=16)),
                ('credit', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('morning_sessions', models.IntegerField(default=4)),
                ('afternoon_sessions', models.IntegerField(default=4)),
                ('lesson_minutes', models.IntegerField(default=45)),
                ('break_minutes', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('index', models.IntegerField()),
            ],
        ),
    ]
