# Generated by Django 5.2.7 on 2025-12-06 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('classrooms', '0001_initial'),
        ('courses', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='organization.major'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='classrooms.classroom'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='organization.class'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='accounts.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('weekday', 'index')},
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='courses.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'edu_level')},
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together={('school_class', 'course', 'timeslot', 'week_number')},
        ),
    ]
