# Generated by Django 5.2.7 on 2025-12-09 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='classroom_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='教室地址'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='organization.major'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='classrooms.classroom'),
        ),
    ]
