# Generated by Django 5.2.7 on 2025-12-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseschedule_classroom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='默认教室地址'),
        ),
    ]
