# Generated by Django 5.2.7 on 2025-12-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_classroom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='edu_level',
        ),
    ]
