# Generated by Django 5.2.7 on 2025-12-17 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_courseschedule_indexes'),
        ('classrooms', '0001_initial'),
        ('courses', '0005_alter_course_unique_together_remove_course_edu_level'),
        ('organization', '0010_add_courseschedule_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['teacher', 'week_number'], name='cs_teacher_week_idx'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['school_class', 'week_number'], name='cs_class_week_idx'),
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['week_number'], name='cs_week_idx'),
        ),
    ]
