# Generated by Django 5.2.7 on 2025-12-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_courseschedule_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
    ]
